services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: railscope
      POSTGRES_USER: railscope
      POSTGRES_PASSWORD: railscope
    ports:
      - "5432:5432"
    volumes:
      - railscope-postgres:/var/lib/postgresql/data
volumes:
  railscope-postgres:
